<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TARge25shop.Core\TARge25shop.Core.csproj" />
    <ProjectReference Include="..\TARge25shop.Data\TARge25shop.Data.csproj" />
  </ItemGroup>

</Project>
